"""Initial migration

Revision ID: 23aec2c70224
Revises: 
Create Date: 2025-11-21 14:21:33.459736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23aec2c70224'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('telegram_id', sa.Integer(), nullable=False),
                    sa.Column('first_name', sa.String(), nullable=False),
                    sa.Column('last_name', sa.String(), nullable=True),
                    sa.Column('phone', sa.String(), nullable=True),
                    sa.Column('registration_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('telegram_id')
                    )
    op.create_table('subscriptions',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('subscription_number', sa.String(), nullable=False),
                    sa.Column('initial_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
                    sa.Column('current_balance', sa.DECIMAL(precision=10, scale=2), nullable=False),
                    sa.Column('start_date', sa.Date(), nullable=False),
                    sa.Column('end_date', sa.Date(), nullable=True),
                    sa.Column('status', sa.String(), nullable=True),
                    sa.Column('visits', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('subscription_number')
                    )
    op.create_table('price_list',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('duration_minutes', sa.Integer(), nullable=False),
                    sa.Column('participants_count', sa.Integer(), nullable=False),
                    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('training_sessions',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('session_date', sa.Date(), nullable=False),
                    sa.Column('session_time', sa.Time(), nullable=False),
                    sa.Column('duration_minutes', sa.Integer(), nullable=False),
                    sa.Column('court_type', sa.String(), nullable=True),
                    sa.Column('coach_name', sa.String(), nullable=True),
                    sa.Column('notes', sa.Text(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('training_participants',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('training_session_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('subscription_id', sa.Integer(), nullable=False),
                    sa.Column('amount_paid', sa.DECIMAL(precision=10, scale=2), nullable=False),
                    sa.Column('participants_count', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['training_session_id'], ['training_sessions.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('transactions',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('subscription_id', sa.Integer(), nullable=False),
                    sa.Column('training_session_id', sa.Integer(), nullable=True),
                    sa.Column('transaction_type', sa.String(), nullable=False),
                    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['training_session_id'], ['training_sessions.id'], ondelete='SET NULL'),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )

    # ### end Alembic commands ###
    # ### Manually added price list data ###
    price_list_table = sa.table('price_list',
                                sa.column('duration_minutes', sa.Integer),
                                sa.column('participants_count', sa.Integer),
                                sa.column('price', sa.DECIMAL),
                                sa.column('description', sa.Text)
                                )
    op.bulk_insert(price_list_table,
                   [
                       {'duration_minutes': 60, 'participants_count': 1, 'price': 1500,
                        'description': 'Индивидуальная 60 мин'},
                       {'duration_minutes': 90, 'participants_count': 1, 'price': 2000,
                        'description': 'Индивидуальная 90 мин'},
                       {'duration_minutes': 120, 'participants_count': 1, 'price': 2500,
                        'description': 'Индивидуальная 120 мин'},
                       {'duration_minutes': 60, 'participants_count': 2, 'price': 800, 'description': 'Вдвоем 60 мин'},
                       {'duration_minutes': 90, 'participants_count': 2, 'price': 1200, 'description': 'Вдвоем 90 мин'},
                       {'duration_minutes': 120, 'participants_count': 2, 'price': 1600,
                        'description': 'Вдвоем 120 мин'},
                       {'duration_minutes': 60, 'participants_count': 3, 'price': 600, 'description': 'Втроем 60 мин'},
                       {'duration_minutes': 90, 'participants_count': 3, 'price': 900, 'description': 'Втроем 90 мин'},
                       {'duration_minutes': 120, 'participants_count': 3, 'price': 1200,
                        'description': 'Втроем 120 мин'},
                       {'duration_minutes': 60, 'participants_count': 4, 'price': 500,
                        'description': 'Вчетвером 60 мин'},
                       {'duration_minutes': 90, 'participants_count': 4, 'price': 750,
                        'description': 'Вчетвером 90 мин'},
                       {'duration_minutes': 120, 'participants_count': 4, 'price': 1000,
                        'description': 'Вчетвером 120 мин'},
                   ]
                   )
    # ### end manually added section ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('training_participants')
    op.drop_table('training_sessions')
    op.drop_table('price_list')
    op.drop_table('subscriptions')
    op.drop_table('users')
    # ### end Alembic commands ###